### ISSUE TITLE
Officially provide PyPi packages

### ISSUE THREAD

**Issue by winterbird-code** [winterbird-code/adbb#13]
I'd like to officially provide a pypi package for adbb, but it seems like @miigotu has already created a pypi-project, so at the moment I do not have access to adbb at pypi.  I have sent an email asking for the project to be transferred, but since the spam filter in gmail isn't really reliable, I'm attempting to use this issue to ping @miigotu.

To be clear, this is not criticism, I think it's great that someone took their time to upload adbb to pypi when I was too lazy to do it. I just think it would be better if I maintained those packages myself from now on.

**Comment by miigotu** [comment]
Absolutely, let me figure out what I need to do real quick with it.

**Comment by miigotu** [comment]
I should have downloaded the sources =P I think there were some fixes in there. Either way, my projects are not using it anymore afaik.

**Comment by winterbird-code** [comment]
The old version is still around [here](https://pypi.org/project/adbb/2/) or by explicit ask pip for adbb version ==2, it's just not advertised.

That said, if you still find adbb useful you should consider using the latest version even if you don't need any of the new features . You will probably have to repopulate the sql cache, but the API should be mostly, if not completely the same, and the UDP session handling is *much* more reliable now.
