### ISSUE TITLE
Trouble checking watched, collected state of episodes?

### ISSUE THREAD

**Issue by Andy2244** [winterbird-code/adbb#3]
Hi, i have trouble getting the watched and file_type/state of a given episode?

```
ep = adbb.Episode(eid=123456)
ep.mylist_state or ep.mylist_viewdate
```
This seems only to work for a specific file? 
If i go to a series i have watched, the anidb http page lists the watched date and file_type under the episodes entries, independent of the actual file data. So what options i have to retrieve this information?

PS: I'm also confused on what the `lid` is and where to use, get it?

**Comment by winterbird-code** [comment]
Yes, the way to do this is to create a generic file. The idea was that it is in fact the files that are in the mylist and not the episodes. lid is the anidb mylist entry ID. If the file you have is in mylist you can access it via the lid-attribute on the file object.

**Comment by Andy2244** [comment]
oki got it thx
